- name: "type:feature"
  color: "1f6feb"
  description: "New feature implementation"
- name: "type:bug"
  color: "d73a4a"
  description: "Defect or regression"
- name: "type:research"
  color: "5319e7"
  description: "Research or investigation"
- name: "type:security"
  color: "b60205"
  description: "Security and privacy work"
- name: "type:idea"
  color: "c5def5"
  description: "Unvalidated idea"
- name: "type:ops"
  color: "0052cc"
  description: "Operational improvement"

- name: "domain:life"
  color: "bfd4f2"
  description: "Personal life logs"
- name: "domain:learning"
  color: "bfdadc"
  description: "Knowledge and learning"
- name: "domain:work"
  color: "c2e0c6"
  description: "Work and project logs"
- name: "domain:people"
  color: "f9d0c4"
  description: "Relationship and person graph"
- name: "domain:money"
  color: "fbca04"
  description: "Budget and purchase decisions"
- name: "domain:health"
  color: "ff9aa2"
  description: "Health-sensitive flows"
- name: "domain:home"
  color: "d4c5f9"
  description: "Home and maintenance"
- name: "domain:travel"
  color: "0e8a16"
  description: "Travel and location logs"
- name: "domain:hobby"
  color: "e99695"
  description: "Creative and hobby"
- name: "domain:decision"
  color: "fef2c0"
  description: "Decision and reflection"

- name: "stage:mvp"
  color: "0366d6"
  description: "MVP stage"
- name: "stage:beta"
  color: "1d76db"
  description: "Beta stage"
- name: "stage:scale"
  color: "0e8a16"
  description: "Scale stage"

- name: "phase:0"
  color: "ededed"
  description: "Foundation"
- name: "phase:1"
  color: "d4c5f9"
  description: "Capture and recall MVP"
- name: "phase:2"
  color: "c2e0c6"
  description: "Auto structuring"
- name: "phase:3"
  color: "bfd4f2"
  description: "Search and retrieval"
- name: "phase:4"
  color: "f9d0c4"
  description: "Conversation assist"
- name: "phase:5"
  color: "fef2c0"
  description: "Automation and agent"
- name: "phase:6"
  color: "fbca04"
  description: "Advanced analytics"

- name: "risk:security"
  color: "b60205"
  description: "Security/privacy risk"
- name: "risk:privacy"
  color: "d93f0b"
  description: "Privacy risk"
- name: "risk:data-loss"
  color: "e99695"
  description: "Potential data loss"

- name: "priority:p0"
  color: "b60205"
  description: "Highest priority"
- name: "priority:p1"
  color: "d93f0b"
  description: "High priority"
- name: "priority:p2"
  color: "fbca04"
  description: "Normal priority"
- name: "priority:p3"
  color: "0e8a16"
  description: "Low priority"

- name: "status:blocked"
  color: "000000"
  description: "Blocked by dependency"
- name: "status:parking"
  color: "cfd3d7"
  description: "Parked for later"
