name: Feature
description: 新機能や改善機能の実装
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: 何を解決したいか
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: 対象範囲（in/out）
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: 完了条件
    validations:
      required: true
  - type: dropdown
    id: phase
    attributes:
      label: Phase
      options:
        - phase0
        - phase1
        - phase2
        - phase3
        - phase4
        - phase5
        - phase6
  - type: dropdown
    id: risk
    attributes:
      label: Risk
      options:
        - low
        - medium
        - high
        - security
